apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-env
data:
  SQLSERVER_HOST: "192.168.100.201" # change to the IP of your SQL Server instance
  SQLSERVER_PORT: "1433"
  SQLSERVER_USER: "sa"
  SQLSERVER_DATABASE: "userDB"

 
