apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      imagePullSecrets:
        - name: acr-secret 
      containers:
        - name: frontend-service
          image: golang.azurecr.io/frontend-service:448
          ports:
            - containerPort: 8082
          env:
            - name: BACKEND_URL
              value: "http://web-service:8081/users"  # Change to the web service URL

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30003
  type: NodePort #ClusterIP  # Exposes the service inside the cluster
